library(ggplot2)
library(maptools)
library(rgeos)
library(ggmap)
library(scales)
library(RColorBrewer)
library(openxlsx)
library(readxl)
library(sf)
set.seed(8000)
shp <- read.csv("C:\\Users\\Santhosh\\Downloads\\newshape\\in\\x.csv")
my_sf <- st_as_sf(shp, coords = c('long', 'lat'))
ggplot(my_sf)+geom_sf()

